### ISSUE TITLE
How to set a default value for a property.

### ISSUE THREAD

**Issue by jonothedev** [spatie/laravel-data#418] opened 2023-04-17 10:55 UTC
### Discussed in https://github.com/spatie/laravel-data/discussions/416

<div type='discussions-op-text'>

<sup>Originally posted by **jonothedev** April 16, 2023</sup>
How can we set a default value for a property? For example, if i were to create a data object, but set a value for a property from two other properties..

```
public string $first_name
public string $last_name
```

Then set a default value for username

`$this->username = $this->first_name . '_' . $this->last_name;`

Is this possible?</div>

**Comment by rubenvanassche** [comment] 2023-04-28 07:59
This is not a bug, so I'm gonna close this. We'll continue in the discussion.

**Closed by rubenvanassche** 2023-04-28 07:59 UTC
