### ISSUE TITLE
Issue with default value on Data class - Missing property

### ISSUE THREAD

**Issue by danielsballes** [spatie/laravel-data#568] opened 2023-09-29 16:35 UTC
I have this class `FiltersData`, I want to use a default value for the `$statuses` property, so my class look like this:

```php
namespace App\Data;

use App\Rules\ValidSupportCaseStatus;
use App\Rules\ValidTrackingType;
use Spatie\LaravelData\Data;

class FiltersData extends Data
{
    public function __construct(
        public array $statuses = [],
        public ?array $offerClickedAt,
        public ?array $lastWorkedOn,
        public ?array $supportTeamMembers,
        public ?array $publishers,
        public ?array $advertisers,
        public ?array $trackingTypes,
        public ?RewardTypesData $rewardTypes,
        public ?bool $escalated,
    ) {
    }

    public static function rules()
    {
        return [
            'statuses' => ['array'],
            'statuses.*' => [new ValidSupportCaseStatus],
            'offerClickedAt' => ['array', 'nullable'],
            'offerClickedAt.*' => ['date_format:Y-m-d H:i:s'],
            'lastWorkedOn' => ['array', 'nullable'],
            'lastWorkedOn.*' => ['date_format:Y-m-d H:i:s'],
            'supportTeamMembers' => ['array', 'nullable'],
            'supportTeamMembers.*.id' => ['exists:users,id'],
            'publishers' => ['array', 'nullable'],
            'publishers.*.pub_id' => ['exists:apps,pub_id'],
            'advertisers' => ['array', 'nullable'],
            'advertisers.*.ad_network_client_id' => ['exists:campaigns,ad_network_client_id'],
            'trackingTypes' => ['array', 'nullable'],
            'trackingTypes.*' => [new ValidTrackingType],
        ];
    }
}
```

I used this class as a nested one on another class used for a request, the main class is this:

```php
namespace App\Data;

use Illuminate\Validation\Rule as ValidationRule;
use Spatie\LaravelData\Data;

class IndexSupportCasesData extends Data
{
    public function __construct(
        public ?int $perPage,
        public ?string $sort,
        public ?string $search,
        public ?string $status_group,
        public ?FiltersData $filters,
    ) {
    }

    public static function rules()
    {
        return [
            'sort' => ['nullable', ValidationRule::in('pub_name', 'status', 'low_payout', 'escalated')],
            'perPage' => ['nullable', 'numeric', ValidationRule::in([25, 50, 100, 200])],
            'status_group' => ['nullable', ValidationRule::in('open', 'closed')],
        ];
    }
}
``` 

But when the request is made the application return this error:
```php
Could not create `App\Data\FiltersData`: the constructor requires 9 parameters, 8 given. Parameters given: offerClickedAt, lastWorkedOn, supportTeamMembers, publishers, advertisers, trackingTypes, rewardTypes, escalated. Parameters missing: statuses.
``` 

**✅ Expected behavior**
The request is fulfilled without errors.

**🖥️ Versions**

Laravel:9.52.15
Laravel Data:3.8.1
PHP:8.1.22

**Comment by Klaas058** [comment] 2023-10-01 08:32
To my understanding even though the `Data` class properties are promoted from the constructor parameters, parameters with default values must be declared after parameters without default values in a function declaration.

Do you get the same error if you move the $statuses parameter to the last parameter position?

Like:

```php
public function __construct(
        public ?array $offerClickedAt,
        public ?array $lastWorkedOn,
        public ?array $supportTeamMembers,
        public ?array $publishers,
        public ?array $advertisers,
        public ?array $trackingTypes,
        public ?RewardTypesData $rewardTypes,
        public ?bool $escalated,
        public array $statuses = [],
  ) {
  }
  ```

**Comment by rubenvanassche** [comment] 2023-10-12 10:19
Can't reproduce:

```php
it('bla', function () {
    class BlaData extends Data
    {
        public function __construct(
            public string $string,
            public array $array = [],
        ) {
        }
    }

    $dataClass = new class(null) extends Data {
        public function __construct(
            public ?BlaData $nested
        ) {
        }
    };

    $data = $dataClass::from((new Request)->merge([
        'nested' => null,
    ]));

    dump($data);

    $data = $dataClass::from((new Request)->merge([
        'nested' => [
            'string' => 'Hello World',
        ],
    ]));

    dump($data);

    $data = $dataClass::from((new Request)->merge([
        'nested' => [],
    ])); // validation error

    dump($data);
});
```

I'm going to close this issue, please let me know if there's a further issue and we'll take a further look.

**Closed by rubenvanassche** 2023-10-12 10:19 UTC
